import org.cthing.gradle.plugins.buildconstants.SourceAccess

plugins {
    id 'java'
    id 'com.gradleup.shadow' version '9.3.1'
    id 'org.cthing.build-constants' version '2.1.0'
}

group = 'dev.JustRed23'
version = '1.2-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    //Parsing args
    implementation "net.sf.jopt-simple:jopt-simple:${joptSimpleVersion}"

    //Logger
    implementation "org.apache.logging.log4j:log4j-core:${log4jVersion}"
    implementation "org.apache.logging.log4j:log4j-api:${log4jVersion}"

    //GSON
    implementation "com.google.code.gson:gson:${gsonVersion}"
}

tasks.register("printVersion") {
    doLast {
        println(project.version)
    }
}

tasks {
    generateBuildConstants {
        classname = "${project.group}.hsm.BuildConstants"
        sourceAccess = SourceAccess.PACKAGE
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.release = 25
}

jar {
    manifest {
        attributes(
                'Main-Class': 'dev.JustRed23.hsm.Main',
                'Implementation-Title': project.name,
                'Implementation-Version': project.version,
                'Implementation-Vendor': 'JustRed23'
        )
    }
}